spring:
  application:
    name: image-update-detector

  cache:
    type: caffeine
    caffeine:
      spec: "maximumSize=500,expireAfterWrite=30m"
server:
  port: 8080
app:
  gitops:
    repo:
    branch:
    token:
    refresh-interval-ms: ${GITOPS_REFRESH_INTERVAL_MS:300000}
  helm-check-interval-ms: ${HELM_CHECK_INTERVAL_MS:600000}

logging:
  level:
    root: INFO
    io.github.martinwitt: DEBUG
