Args = --initialize-at-run-time=org.hibernate.validator.internal.util.logging.Messages \
       --initialize-at-run-time=org.hibernate.validator.resourceloading.PlatformResourceBundleLocator \
       --initialize-at-run-time=org.hibernate.validator.resourceloading.AggregateResourceBundle
